version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=standalone
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
    driver: local
