#!/usr/bin/env bash

# Create our VPC

VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--tag-specification 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-3}]' \  
--region us-east-1 \
--query Vpc.VpcId
--output text)

echo $VPC_ID

# Create an IGW

# Attach an IGW

# Create a new subnet

# Explicitly Associate subnet

# Add a route for our RT to our IGW
