#!/usr/bin/env bash
echo ".. create bucket"

# Check for bucket name
if [ -z "$1" ]; then
  echo "Error: There need to be a bucket name provided."
  exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket --bucket $BUCKET_NAME \
--region us-east-1 \
--query Location \
--output text

