#!/usr/bin/env bash

echo ".. put object"

# Check for bucket name
if [ -z "$1" ]; then
  echo "Error: There need to be a bucket name provided."
  exit 1
fi

# Check for filename 
if [ -z "$2" ]; then
  echo "Error: There need to be a file name provided."
  exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY