# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html

AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ImageId:
    Type: String
      imageId: ami-276181762565611716
Resources:
   MyEC2Instance:
     Type: 'AWS::EC2::Instance'
     Properties: 
        LaunchTemplate:
          LaunchTemplateId: !Ref myLaunchTemplate
          Version: !GetAtt myLaunchTemplate.DefaultVersionNumber
   myLaunchTemplate:
     Type: 'AWS::EC2::LaunchTemplate'
     Properties:
       LaunchTemplateData:
          ImageId: ami-0a70b9d193ae8a799
          InstanceType: t2.micro
          MetadataOptions: 
            InstanceMetadataTags: enabled
          SecurityGroupIds:
            - sg-12a4c434
          TagSpecifications:
            - ResourceType: instance
              Tags:
              - Key: department
                Value: dev


      #!/bin/bash
      yum update -y
      yum install -y httpd
      systemctl start httpd
      systemctl enable httpd
      echo "<html><body><h1>Hello from apache on amazon Linux 2!</h1></body></html>" > /var/www/html/index.html